// <auto-generated />
using System;
using Horga_Alexandra_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Horga_Alexandra_Proiect.Migrations
{
    [DbContext(typeof(Horga_Alexandra_ProiectContext))]
    [Migration("20240113094032_FullName")]
    partial class FullName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Asistent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Asistent");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.CategoriePacient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("PacientID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("PacientID");

                    b.ToTable("CategoriePacient");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Doc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doc");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Pacient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Afectiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AsistentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConsultatie")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocID")
                        .HasColumnType("int");

                    b.Property<string>("Doctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AsistentID");

                    b.HasIndex("DocID");

                    b.ToTable("Pacient");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.CategoriePacient", b =>
                {
                    b.HasOne("Horga_Alexandra_Proiect.Models.Categorie", "Categorie")
                        .WithMany("CategoriePacient")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horga_Alexandra_Proiect.Models.Pacient", "Pacient")
                        .WithMany("CategoriePacient")
                        .HasForeignKey("PacientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Pacient", b =>
                {
                    b.HasOne("Horga_Alexandra_Proiect.Models.Asistent", "Asistent")
                        .WithMany("Pacienti")
                        .HasForeignKey("AsistentID");

                    b.HasOne("Horga_Alexandra_Proiect.Models.Doc", "Doc")
                        .WithMany("Pacienti")
                        .HasForeignKey("DocID");

                    b.Navigation("Asistent");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Asistent", b =>
                {
                    b.Navigation("Pacienti");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Categorie", b =>
                {
                    b.Navigation("CategoriePacient");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Doc", b =>
                {
                    b.Navigation("Pacienti");
                });

            modelBuilder.Entity("Horga_Alexandra_Proiect.Models.Pacient", b =>
                {
                    b.Navigation("CategoriePacient");
                });
#pragma warning restore 612, 618
        }
    }
}
